class ApiTags:
    serviceTag = 'service'
    nameTag = 'name'
    descriptionTag = 'description'
    realmTag = 'realm'
    namespaceTag = 'namespace'
    constantsTag = 'constants'
    domainObjectsTag = 'domain_objects'
    structTag = 'struct'
    enumTag = 'enum'
    aliasTag = 'alias'
    fieldsTag = 'fields'
    valuesTag = 'values'
    valueTag = 'value'
    typeTag = 'type'
    processTag = 'process'
    uriTag = 'uri'
    argumentsTag = 'arguments'
    constTag = 'const'
    eventsTag = 'events'
    topicTag = 'topic'
    importsTag = 'imports'
    moduleTag = 'module'


class ApiTypes:
    charType = 'char'
    unsignedCharType = 'unsigned char'
    shortIntegerType = 'short integer'
    unsignedShortIntegerType = 'unsigned short integer'
    integerType = 'integer'
    unsignedIntegerType = 'unsigned integer'
    longIntegerType = 'long integer'
    unsignedLongIntegerType = 'unsigned long integer'
    shortFloatingType = 'short floating'
    floatingType = 'floating'
    stringType = 'string'
    booleanType = 'boolean'
    uriType = 'uri'


class ApiAccess:
    asyncAccess = 'async'
    asyncPagedAccess = 'async_paged'
